language: php
cache:
    directories:
        - node_modules
        - ~/.npm
        - vendor
php:
    - '7'
git:
    depth: 3
script:
    - composer install
    - vendor/bin/phpunit
notifications:
    email:
        recipients:
            - devalexandrecr@gmail.com
        on_success: always
        on_failure: always
    slack: 
        secure: "bbayagVtILz8lx3p2Psd0W2qmUYPz3vfd4iKhCI81NAbF/hGCl3VWQqTvGNABGtapg0L2YV8QqBTPbQ08iIO3hZnfCnwUZFAKuIy2MchlWvhtQQ3b5qPU00lKZEWjQs5rrQRn
        EeitGwRaoGU9pdVNsivc1MEg/MUXssk7yXAFjH9p0blk2xHGf8E1oXZuCD2+RogFTBKtO36qCRpJFBTnT+ztXuIOsxzrrzmoUYoOAf5yrCIPsv0vikHhDmq59/9gZGEym/gGWpuBjioQFns3
        HkKUc19lZkjlVgyXIRIrTtPJGwT23/nsm6rOL8kYk6vCL+FUnrJCI9zVJC1k81R0aosa/4qEQXkFbS2IXGrbX81CgPDwaLaHIAq7xO8dL4duFq0HnLfYLHIf+rewACmTy08K7CZHUbjl2Gti
        G+YhnRNg3QI+XglrgmGw2zDOYTUW83VCZolWMVGQmJOLMrM97xDqRfxeFlrRAedGh+uW5UpyaUqy8fTA9DfWPUs0cKtEZ9K7TrHtB8227xtFrINW9+45/2rqVKZjbYyKimg05DRgExRAwZks
        KyCZTl01VmGKGZRrNcwYVc+DHXJxGwrzEpmW2BWv2EFXhddqBZZLfR2QQAng1VhCnj7tzA0yNBYjrEQ2IT3Qp+Ay3+GGqTOwiY7uYx27vTHqzBu9kthMkQ="
deploy:
    provider: heroku
    skip-cleanup: true
    keep-history: true
    api_key: 
        secure: g+fHbiqVnqGerrkL9o3DgQ79H3LBNdHBC/BJ1h5V1wQIUl1wxrqTYKJ/oQAMMGXrR3A7oGwc3YNlkYbBqItkkVV6vg6W2d/ZKPw3pqIbhPiYdswpVUFnNvAL1ra3k9lMlsNEpIBWYJYOSA6mmkY4es6+/ZNCEr
        c7BVcw2F8ACw/ZiPfMm/AexV+nSxrzacWlJOdkIvDef7E8SoFnwZd6RATXMN6Ogjcln9cTPvK2R3Kk6FR0s6xxtijJHqhw3B3F2gGNhbG0elWNUzG8TQEmTi4R7IZnqXLmzWUJhDDRJrcIU7aQJLp8pfG8rcXDkOu0LGlUQUIP
        HOEgckJa+H5FYxUFKIz90r0S5g53THsWrQtVzOOMr3GEozHc1mJmato3yvWev9H3ghOwDfCzuTIaK3XaD8Q1tYbDMA4ZIBkAsA7bo8C21/9bFbyOEHhYqBm/cO0wd6Tv553ITwr+Zmkc/fxHV0psHgLIJtcDHrtx2v2qX9DOFr
        VViSAfd/XIurDoPBfRckmCHE/n9Z/lEswR+wTRCpdgxO9lOngy5gL8z/C6aCcn3ACNVCIkoruHd++o6UK4uQBP7YA3POUKhsGYGPaN+Jwyn1ZoXUVHgC6Bkj9sU46G+5VN4rJFvetANGMd9MoZH7cxhRn27BoFxYJt9/2kYPYl
        aVp7nl1SQ61B1cY=
    app: lokerstore
    on:
        repo:  DevAlexandreCR/lokerstore