<?php

namespace Tests\Feature\Http\Controllers\Admin;

use App\Constants\Admins;
use App\Constants\Roles;
use App\Models\Admin\Admin;
use App\Models\OrderDetail;
use App\Models\Stock;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use OrderSeeder;
use StockSeeder;
use TestDatabaseSeeder;
use Tests\TestCase;
use UserSeeder;

class OrderDetailsControllerTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    private $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed([
            TestDatabaseSeeder::class,
            UserSeeder::class,
            StockSeeder::class,
            OrderSeeder::class
        ]);

        $this->admin = factory(Admin::class)->create();
        $this->admin->assignRole(Roles::ADMIN);
        $this->withoutExceptionHandling();
    }

    public function testAnAdminCanUpdateAnOrderDetail(): void
    {
        $stock = factory(Stock::class)->create([
            'quantity' => 10
        ]);

        $detail = factory(OrderDetail::class)->create([
            'stock_id' => $stock->id,
            'quantity' => 5
        ]);

        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->patch(route('order_details.update', $detail->id),
        [
            'stock_id' => $detail->stock_id,
            'quantity' => 3
        ]);

        $response
            ->assertStatus(302)
            ->assertRedirect(route('orders.show', $detail->order_id))
            ->assertSessionHas('success');

        $this->assertDatabaseHas('order_details', [
            'id' => $detail->id,
            'quantity' => 3
        ]);

        $this->assertDatabaseHas('stocks', [
            'id' => $detail->stock_id,
            'quantity' => 7
        ]);
    }

    public function testAnAdminCanDeleteAnOrderDetail(): void
    {
        $detail = OrderDetail::all()->random();
        $id = $detail->id;

        $response = $this->actingAs($this->admin, Admins::GUARDED)
            ->delete(route('order_details.destroy', $detail->id));

        $response
            ->assertStatus(302)
            ->assertRedirect(route('orders.show', $detail->order_id))
            ->assertSessionHas('success');

        $this->assertDatabaseMissing('order_details', [
            'id' => $id
        ]);
    }
}
