<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Models\Photo;
use TestDatabaseSeeder;
use App\Models\Product;
use App\Constants\Roles;
use App\Models\Admin\Admin;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ApiPhotosControllerTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    private Admin $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed([
            TestDatabaseSeeder::class
        ]);

        $this->admin = factory(Admin::class)->create();
        $this->admin->assignRole(Roles::ADMIN);
    }

    public function testAnAdminAuthenticatedCanStorePhotos(): void
    {
        Storage::fake('public_photos');

        $product = factory(Product::class)->create();
        $file = UploadedFile::fake()->image('test.jpeg')->mimeType('image/jpeg');
        $file2 = UploadedFile::fake()->image('test2.jpeg')->mimeType('image/jpeg');

        $response = $this->postJson(route('api.photos.store'), [
            'api_token'  => $this->admin->api_token,
            'product_id' => $product->id,
            'photos'     => [$file, $file2]
        ]);

        $response
            ->assertStatus(200)
            ->assertJsonFragment([
                'status' => [
                    'status' => 'OK',
                    'message' => 'Photo saved successfully',
                    'code'    => 200
                ]
            ]);
//        $this->assertDatabaseHas('photos', [
//            'product_id' => $product->id
//        ]);
    }

    public function testAnAdminAuthenticatedCanDeleteAPhoto(): void
    {
        Storage::fake('public_photos');

        $product = Product::all()->random();

        $photo = factory(Photo::class)->create([
            'product_id' => $product->id
        ]);

        $response = $this->deleteJson(route('api.photos.destroy'), [
            'api_token'  => $this->admin->api_token,
            'photos' => [
                $photo->id
            ]
        ]);

        $response
            ->assertStatus(200)
            ->assertJsonFragment([
                'status' => [
                    'status' => 'OK',
                    'message' => 'Photo removed successfully',
                    'code'    => 200
                ]
            ]);
        $this->assertDatabaseMissing('photos', [
            'id' => $photo->id,
            'product_id' => $photo->product_id,
            'name' => $photo->name
        ]);
    }
}
