<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Models\Size;
use App\Models\Color;
use App\Models\Product;
use App\Models\Category;
use App\Constants\Roles;
use App\Models\Admin\Admin;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use TestDatabaseSeeder;
use Tests\TestCase;

class ApiProductControllerTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    private Admin $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed([
            TestDatabaseSeeder::class
        ]);

        $this->admin = factory(Admin::class)->create();
        $this->admin->assignRole(Roles::ADMIN);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testAnyUserCanViewProductsList(): void
    {
        $response = $this->json('GET', route('api.index'));

        $response->assertJson(Product::all()->toArray());
    }

    public function testAnyUserCanViewAProduct(): void
    {
        $product = factory(Product::class)->create();

        $response = $this->json('GET', route('api.show', [
            'product' => $product->id
        ]));

        $response
            ->assertStatus(200)
            ->assertJsonFragment([
            'status' => [
                'status' => 'OK',
                'message' => 'Product was found',
                'code'    => 200
            ]
        ]);
    }

    public function testAnAdminAuthenticatedCanCreateAProduct(): void
    {
        $category = Category::all()->random()->id;
        $size1 = Size::all()->random();
        $color1 = Color::all()->random()->name;
        $size2 = Size::all()->random();
        $color2 = Color::all()->random()->name;
        $file = UploadedFile::fake()->image('test.jpeg')->mimeType('image/jpeg');

        $response = $this->postJson(route('api.products.store'), [
            'api_token'     => $this->admin->api_token,
            'id_category'   => $category,
            'name'          => 'new product',
            'description'   => 'This product is amazing and great for you',
            'tags'          => ['Hombre'],
            'price'         => 25000,
            'stocks'        => [
                0 => [
                    'color' => $color1,
                    'size'  => [
                        'type' => $size1->type->name,
                        'size' => $size1->name
                    ],
                    'quantity' => 1
                ],
                1 => [
                    'color' => $color2,
                    'size'  => [
                        'type' => $size2->type->name,
                        'size' => $size2->name
                    ],
                    'quantity' => 5
                ]
            ],
            'photos' => [
                $file,
            ]
        ]);

        $response
            ->assertStatus(200)
            ->assertJson([
                'status' => [
                    'status' => 'OK',
                    'message' => 'Product was created successfully'
                ],
                'product' => [
                    'id_category'   => $category,
                    'name'          => 'new product',
                    'description'   => 'This product is amazing and great for you',
                ]
            ]);

        $this->assertDatabaseHas('products', [
            'name'          => 'new product',
            'description'   => 'This product is amazing and great for you',
        ]);
    }

    public function testAnAdminAuthenticatedCanUpdateAProduct(): void
    {
        $product = Product::all()->random();

        $category = Category::all()->random()->id;

        $response = $this->putJson(route('api.products.update', $product->id),[
            'api_token'     => $this->admin->api_token,
            'id_category'   => $category,
            'name'          => 'Update product',
            'description'   => 'This product is amazing and great for you, but were updated',
            'tags'          => ['Mujer'],
            'price'         => 25000,
        ] );

        $response
            ->assertStatus(200)
            ->assertJson([
                'status' => [
                    'status' => 'OK',
                    'message' => 'Product was updated successfully'
                ],
                'product' => [
                    'id_category'   => $category,
                    'name'          => 'Update product',
                    'description'   => 'This product is amazing and great for you, but were updated',
                ]
            ]);

        $this->assertDatabaseHas('products', [
            'id_category'   => $category,
            'name'          => 'Update product',
            'description'   => 'This product is amazing and great for you, but were updated',
        ]);
    }

    public function testAnAdminAuthenticatedCanRemoveAProduct(): void
    {
        $product = Product::all()->random();

        $response = $this->deleteJson(route('api.products.destroy', $product->id), [
            'api_token'     => $this->admin->api_token,
        ]);

        $response
            ->assertStatus(200)
            ->assertJson([
                'status' => [
                    'status' => 'OK',
                    'message' => 'Product was deleted successfully'
                ]
            ]);
        $this->assertDatabaseMissing('products', [
            'id' => $product->id
        ]);
    }
}
