<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Models\Product;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use TestDatabaseSeeder;
use Tests\TestCase;

class ProductControllerTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed([
            TestDatabaseSeeder::class
        ]);

        $this->user = factory(User::class)->create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testIndex(): void
    {
        $response = $this->json('GET', route('api.index'));

        $response->assertJson(Product::all()->toArray());
    }

    public function testShow(): void
    {
        $product = factory(Product::class)->create();

        $response = $this->actingAs($this->user)->json('GET', route('api.show', [
            'product' => $product->id
        ]));

        $response->assertStatus(200);
        $response->assertJsonStructure([
            'data' => ['name', 'created_at', 'updated_at']
        ]);
    }
}
