<?php

namespace Tests\Feature\Http\Controllers\Web;

use App\Models\Cart;
use App\Models\Category;
use App\Models\Color;
use App\Models\Photo;
use App\Models\Product;
use App\Models\Size;
use App\Models\Stock;
use App\Models\Tag;
use App\Models\TypeSize;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class OrderControllerTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
        $this->user = factory(User::class)->create([
            'is_active' => true,
            'email_verified_at' => now()
        ]);
        $this->user->cart = factory(Cart::class)->create([
            'user_id' => $this->user->id
        ]);
        $stock = $this->createProductRelations();

        $this->user->cart->stocks()->attach($stock->id, ['quantity' => 2]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testStore()
    {
        $response = $this->actingAs($this->user)
            ->post(route('user.order.store', $this->user),
            [
                'user_id' => $this->user->id
            ]);

        $response->assertStatus(200);

        $this->assertDatabaseHas('orders',
        [
            'user_id' => $this->user->id
        ]);
    }

    public function createProductRelations(): Stock
    {
        $categories = [
            'RopaTest','ZapatosTest','DeportesTest','AccesoriosTest'
        ];
        foreach ($categories as $name) {
            factory(Category::class)->create([
                'name' => $name,
                'id_parent' => null
            ]);
        }
        factory(Category::class, 2)->create();
        $tag = factory(Tag::class)->create();
        $product = factory(Product::class)->create();
        $product->tags()->attach($tag->id);
        factory(Photo::class, rand(1, 5))->create([
            'product_id' => $product->id
        ]);
        factory(TypeSize::class)->create();
        factory(Size::class)->create();
        factory(Color::class)->create();

        return factory(Stock::class)->create([
            'quantity' => 5
        ]);
    }
}
